name: Chal-2048

on:
  push:
    branches: ["main"]
    paths:
      - "!**/README.md"
      - "challenges/pwn/2048/**"
  workflow_dispatch:

env:
  TYPE: pwn
  NAME: "2048"
  REGISTRY: ghcr.io

jobs:
  challenge-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile
        run: |
          cd challenges/${{ env.TYPE }}/${{ env.NAME }}/build
          gcc src/2048.c -o 2048
          mkdir -p ../attachments
          cp 2048 ../attachments/2048

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/pwn-${{ env.NAME }}
          tags: |
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: challenges/${{ env.TYPE }}/${{ env.NAME }}/build
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Check if attachments exist
        id: check
        run: |
          if [ -d "challenges/${{ env.TYPE }}/${{ env.NAME }}/attachments" ]; then
            echo "attachments_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "attachments_exist=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload attachments
        uses: actions/upload-artifact@v3
        if: ${{ steps.check.outputs.attachments_exist == 'true' }}
        with:
          name: ${{ env.NAME }}
          path: challenges/${{ env.TYPE }}/${{ env.NAME }}/attachments/
